version: "3.7"
services:
  db:
    image: "mysql:8.0.23"
    ports:
      - 3306:3306
    restart: always
    environment:
      #      MYSQL_DATABASE: ticktap
      #MYSQL_USER: ticktapuser
      MYSQL_ROOT_PASSWORD: mysecretpassword
